sudo: required

services:
- docker

language: node_js
node_js:
  - lts/*

cache: yarn

script:
  yarn test

deploy:
- provider: script
  script: bash docker_push.sh
  on:
    branch: develop

- provider: script
  script: bash docker_push.sh
  on:
    tags: true
